halaman_login/urls.py
from django.conf.urls import url
from .views import index,login,registrasi

#url for app
urlpatterns = [
	url(r'^$',index, name='index'),
	url(r'^login/',login, name='login'),
	url(r'^registrasi/',registrasi, name='registrasi')
	# url(r'^halaman_utama_donatur/$',halaman_utama_donatur, name='halaman_utama_donatur')
	# url(r'^halaman_utama_mahasiswa/$',halaman_utama_mahasiswa, name='halaman_utama_mahasiswa')
	# url(r'^halaman_utama_admin/$',halaman_utama_admin, name='halaman_utama_admin')
]

tkBasdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_login.urls as halaman_login
import pendaftaran_paket_beasiswa.urls as pendaftaran_paket_beasiswa
import daftar_beasiswa.urls as daftar_beasiswa
import informasi_beasiswa.urls as informasi_beasiswa
import penerimaan_beasiswa.urls as penerimaan_beasiswa

urlpatterns = [
    url(r'^$',include(halaman_login, namespace='index')),
    url(r'^admin/', admin.site.urls),
    url(r'^pendaftaran-beasiswa/', include(pendaftaran_paket_beasiswa, namespace='pendaftaran_paket_beasiswa')),
    url(r'^login/',include(halaman_login, namespace='login')),
    url(r'^registrasi/',include(halaman_login, namespace='registrasi')),
    url(r'^daftar/',include(daftar_beasiswa, namespace='daftar_beasiswa')),
    url(r'^informasi/', include(informasi_beasiswa, namespace='informasi_beasiswa')),
    url(r'^penerimaan/', include(penerimaan_beasiswa, namespace='penerimaan_beasiswa')),

    ]

halaman_login/models.py
from django.db import models

# Create your models here.

halaman_login/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect, csrf_exempt

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

# Create your views here.
def index(request):
    response ={}
    html = "halaman_login/Halaman_Utama.html"
    return render(request,html,response)

def login(request):
    response ={}
    html = "halaman_login/login.html"
    return render(request,html,response)

def auth(request):
    username = request.POST['username']
    password = request.POST['password']
    cursor=connection.cursor()
    cursor.execute("SELECT * from pengguna where username='"+username+"'")
    hasil=cursor.fetchone();
    if (hasil):
        cursor.execute("SELECT password from pengguna where username='"+username+"'")
        hasil=cursor.fetchone();
        if (hasil[0]==password):
            request.session['username']=username
            cursor.execute("SELECT role from pengguna where username='"+username+"'")
            hasil=cursor.fetchone();
            request.session['role'] = hasil[0]
            if (hasil[0]!="admin"):
                role=hasil[0]
                return HttpResponseRedirect(reverse('Halaman_Utama_Mahasiswa.html'))
                if (role!="mahasiswa"):
                    role="donatur"
                    return HttpResponseRedirect(reverse('Halaman_Utama_Donatur.html'))
                cursor.execute("SELECT nama from " +role+ " where username='"+username+"'")
                hasil=cursor.fetchone();
                request.session['nama']=hasil[0]

            return HttpResponseRedirect(reverse('Halaman_Utama_Admin'))
    messages.error(request, "Username atau password salah")
    return HttpResponseRedirect(reverse('account:login'))




def registrasi(request):
    response ={}
    html = 'halaman_login/Registrasi.html'
    return render(request, html,response)

# def halaman_utama_admin(request):
#     response['status'] = {'status': 'true'}
#     html = 'Halaman_Utama_Admin.html'
#     return render(request, html,response)

# def halaman_utama_donatur(request):
#     response['status'] = {'status': 'true'}
#     html = 'Halaman_Utama_Donatur.html'
#     return render(request, html,response)

# def halaman_utama_mahasiswa(request):
#     response['status'] = {'status': 'true'}
#     html = 'Halaman_Utama_Mahasiswa.html'
#     return render(request, html,response)

halaman_login/templates/halaman_login/Halaman_Utama.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome to SIMBION</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
        <style>
            html,body{
              margin:0;
              padding:0;
              height:100%;
              width:100%;
            }
            
            .table{
              width: 100%;
              height:90%;
            }

            .intro{
              height :99%;
              width : 100%;
              margin: auto;
              background: url("./IMG_0561.JPG");
              display:table;
              top :0;
              background-size: cover;
            }

            .intro .inner{
              display: table-cell;
              vertical-align : middle;
              width:100%;
              max-width:none;
            }

            .content{
              max-width: width 500px;
              margin:0 auto;
              text-align: center;
              font-family: Raleway;
              color:white;
            }
    
            #footer-black{
              /* position: fixed; */
              left: 0;
              bottom: 0;
              background-color:black;
              box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
              box-sizing: border-box;
              width: 100%;
              text-align: left;
              font: bold 16px sans-serif;
              padding: 25px 0;
              margin-top: 80px;
            }

            h1{
              font-size: 80px;
            }

            hr {
              max-width: 50px;
              border-width: 3px;
              border-color: #F05F40;
            }

            #mainNav {
              position: fixed;
              right: 0;
              left:0;
              padding: 5px;
              background-color: #212529;
            }

            #mainNav .navbar-toggler {
              font-size: 12px;
              right: 0;
              padding: 13px;
              text-transform: uppercase;
              color: white;
              border: 0;
              background-color: white;
              font-family: 'Montserrat', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            }

            #mainNav .navbar-brand {
              color: white;
              font-family: 'Kaushan Script', 'Helvetica Neue', Helvetica, Arial;
            }
            
            .nav-link{
              color: white;
            }

            #mainNav .navbar-brand.active, #mainNav .navbar-brand:active, #mainNav .navbar-brand:focus, #mainNav .navbar-brand:hover {
              color: white;
            }

            .inlist{
              height :80%;
              width : 80%;
              margin: auto;
            }

            .fixed_header{
                width: 998px;
                table-layout: fixed;
                border-collapse: collapse;
                border: black;
            }

            .fixed_header tbody{
              display:block;
              width: 1000px;
              overflow: auto;
              height: 100px;
            }

            .fixed_header thead tr {
              display: block;
            }

            .fixed_header thead {
              background: black;
              color:#fff;
            }

            .fixed_header th, .fixed_header td {
              border: 1px solid #dddddd;
              text-align: left;
              padding: 8px;
            }

            tr:nth-child(even) {
              background-color: #dddddd;
            }
            
            .bg-light{
              background-color: #e7e5e5;
              height :80%;
              width : 100%;
              margin: auto;
            }
            .product_view .modal-dialog{
              max-width: 1200px; width: 100%;
            }
            .pre-cost{
              text-decoration: line-through; 
              color: #a5a5a5;
            }
            .space-ten{
              padding: 10px 0;
            }
            span.tags 
            {
                border-radius: 2px;
                width: 100%
                font-weight: bold;
                padding: 2px 4px;
                background:lightblue;
                }
                                
  </style>
        <nav id="mainNav">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <!-- <a class="navbar-brand" href="#">WebSiteName</a>  -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                    </button>
                  </div>
                  <ul class="nav navbar-nav">
                    <li class="active"><a class="navbar-brand js-scroll-trigger" href="#home">Home</a></li>
                    <li><a class="nav-link js-scroll-trigger" href="#list-beasiswa">List Beasiswa</a></li>
                    <li><a class="nav-link js-scroll-trigger" href="#pengumuman">Pengumuman</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'registrasi:registrasi' %}" class="nav-link"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                    <li><a href="{% url 'login:login' %}" class="nav-link"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                  </ul>
                </div>
              </nav>
    </head>
    <body>
              <!-- Home -->
              <section id="home" class="intro">
                <div class="inner">
                    <div class="content">
                        <h1>
                            <strong> Sistem Informasi Beasiswa Universitas X </strong>
                        </h1>
                    <hr>
                    <h3> Portal Beasiswa </h3>
                    </div>
                </div>
              </section>
              <br>
              <br>
              <!-- list beasiswa -->
              <section id="list-beasiswa" class="inlist">
                <div>
                    <h2>
                        <center><strong> Daftar Beasiswa</strong></center>
                    </h2>
                </div>
                <hr>
                <div>
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Nama Beasiswa</th>
                        <th>Waktu Tutup Pendaftaran</th>
                        <th>Status</th>
                        <th>Jumlah Pendaftar</th> 
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>Beasiswa Penuh RFG Foundation Indonesia</td>
                        <td>8 April 2018</td>
                        <td>Ditutup</td>
                        <td>23</td>
                        <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#beasiswa1"><i class="fa fa-search"></i>Lihat Beasiswa</button></td>
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>Beasiswa Kurang Mampu Hogan Ruspine</button></td>
                        <td>5 Juni 2018</td>
                        <td>Dibuka</td>
                        <td>1</td>
                        <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#beasiswa2"><i class="fa fa-search"></i>Lihat Beasiswa</button></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div class="modal fade product_view" id="beasiswa1">
                <div class="modal-dialog">
                   <div class="modal-content">
                      <div class="modal-header">
                        <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                        <h3 class="modal-title">Beasiswa Penuh RFG Foundation Indonesia - 2</h3>
                      </div>
                    <div class="modal-body">
                      <div class="row">
                        <div class="col-md-6 product_content">
                          <p>Beasiswa penuh dibuat oleh D00002</p>
                          <p>Beasiswa Penuh RFG Foundation Indonesia</p>
                          <p>Syarat: 
                            <span class="tags">Tidak Merokok</span> 
                            <span class="tags">Tidak Pernah Mengulang Mata Kuliah</span>
                            <span class="tags">Warga Negara Indonesia</span>
                          </p>
                        </div>
                      </div>
                  </div>
                </div>
              </div>

              <div class="modal fade product_view" id="beasiswa2">
                <div class="modal-dialog">
                   <div class="modal-content">
                      <div class="modal-header">
                        <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                        <h3 class="modal-title">Beasiswa Kurang Mampu Hogan Ruspine - 46</h3>
                      </div>
                    <div class="modal-body">
                      <div class="row">
                        <div class="col-md-6 product_content">
                          <p>Beasiswa penuh dibuat oleh D00046</p>
                          <p>Beasiswa Kurang Mampu Hogan Ruspine</p>
                          <p>Syarat: 
                            <span class="tags">Warga Negara Indonesia</span> 
                            <span class="tags">Memiliki prestasi dalam bidang akademik</span>
                            <span class="tags">Lancar dalam bahasa Inggris</span>
                          </p>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
      </div>
    </div>
  </div>
          </section>

              <!-- pengumuman -->
              <br>
              <br>
              <section id="pengumuman" class="bg-light">
                <br>
                <br>
                  <div>
                      <h2>
                          <center><strong> Pengumuman</strong></center>
                      </h2>
                  </div>
                  <hr>
              </section>
    </body>
    <footer id="footer-black">
      <div>
          <div class="container">
              <div class="row">
                    <p>© Copyright 2018. K18Basdat. All Rights Reserved. <span class="pull-right"><a href="#">Privacy</a> | <a href="#">ToS</a> | <a href="#">Contact</a></span></p>
              </div>
            </div>
        </div>
      </div>
    </footer>

</html>

halaman_login/templates/halaman_login/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Login</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style>
            html,body{
              margin:0;
              padding:0;
              height:100%;
              width:100%;
              background: url("./IMG_0561.JPG");
            }

            #mainNav{
                background-color:  #212529;
            }
    
            #mainNav .navbar-toggler {
              font-size: 12px;
              right: 0;
              padding: 13px;
              text-transform: uppercase;
              color: white;
              border: 0;
              
              font-family: 'Montserrat', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            }

            #mainNav .navbar-brand {
              color: white;
              font-family: 'Kaushan Script', 'Helvetica Neue', Helvetica, Arial;
            }
            
            .nav-link{
              color: white;
            }

            #mainNav .navbar-brand.active, #mainNav .navbar-brand:active, #mainNav .navbar-brand:focus, #mainNav .navbar-brand:hover {
              color: white;
            }
            

            .wrapper {
              display: flex;
              align-items: center;
              flex-direction: column; 
              justify-content: center;
              width: 100%;
              min-height: 100%;
              padding: 50px;
            }

            #formContent {
              -webkit-border-radius: 10px 10px 10px 10px;
              border-radius: 10px 10px 10px 10px;
              background: #fff;
              padding: 30px;
              width: 90%;
              max-width: 450px;
              position: relative;
              padding: 0px;
              -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
              box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
              text-align: center;
            }

            #formFooter {
              background-color: #f6f6f6;
              border-top: 1px solid #dce8f1;
              padding: 25px;
              text-align: center;
              -webkit-border-radius: 0 0 10px 10px;
              border-radius: 0 0 10px 10px;
            }

            /* TABS */

            h2.inactive {
              color: #cccccc;
            }

            h2.active {
              color: #0d0d0d;
              border-bottom: 2px solid #5fbae9;
            }

            /* FORM TYPOGRAPHY*/

            input[type=button], input[type=submit], input[type=reset]  {
              background-color: #56baed;
              border: none;
              color: white;
              padding: 15px 80px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
              text-transform: uppercase;
              font-size: 13px;
              -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
              box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
              -webkit-border-radius: 5px 5px 5px 5px;
              border-radius: 5px 5px 5px 5px;
              margin: 5px 20px 40px 20px;
              -webkit-transition: all 0.3s ease-in-out;
              -moz-transition: all 0.3s ease-in-out;
              -ms-transition: all 0.3s ease-in-out;
              -o-transition: all 0.3s ease-in-out;
              transition: all 0.3s ease-in-out;
            }

            input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
              background-color: #39ace7;
            }

            input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
              -moz-transform: scale(0.95);
              -webkit-transform: scale(0.95);
              -o-transform: scale(0.95);
              -ms-transform: scale(0.95);
              transform: scale(0.95);
            }

            input[type=text] {
              background-color: #f6f6f6;
              border: none;
              color: #0d0d0d;
              padding: 15px 32px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
              font-size: 16px;
              margin: 5px;
              width: 85%;
              border: 2px solid #f6f6f6;
              -webkit-transition: all 0.5s ease-in-out;
              -moz-transition: all 0.5s ease-in-out;
              -ms-transition: all 0.5s ease-in-out;
              -o-transition: all 0.5s ease-in-out;
              transition: all 0.5s ease-in-out;
              -webkit-border-radius: 5px 5px 5px 5px;
              border-radius: 5px 5px 5px 5px;
            }

            input[type=text]:focus {
              background-color: #fff;
              border-bottom: 2px solid #5fbae9;
            }

            input[type=text]:placeholder {
              color: #cccccc;
            }


            input[type=password] {
              background-color: #f6f6f6;
              border: none;
              color: #0d0d0d;
              padding: 15px 32px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
              font-size: 16px;
              margin: 5px;
              width: 85%;
              border: 2px solid #f6f6f6;
              -webkit-transition: all 0.5s ease-in-out;
              -moz-transition: all 0.5s ease-in-out;
              -ms-transition: all 0.5s ease-in-out;
              -o-transition: all 0.5s ease-in-out;
              transition: all 0.5s ease-in-out;
              -webkit-border-radius: 5px 5px 5px 5px;
              border-radius: 5px 5px 5px 5px;
            }

            input[type=password]:focus {
              background-color: #fff;
              border-bottom: 2px solid #5fbae9;
            }

            input[type=password]:placeholder {
              color: #cccccc;
            }

            /* ANIMATIONS */

            /* Simple CSS3 Fade-in-down Animation */
            .fadeInDown {
              -webkit-animation-name: fadeInDown;
              animation-name: fadeInDown;
              -webkit-animation-duration: 1s;
              animation-duration: 1s;
              -webkit-animation-fill-mode: both;
              animation-fill-mode: both;
            }

            @-webkit-keyframes fadeInDown {
              0% {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
              }
              100% {
                opacity: 1;
                -webkit-transform: none;
                transform: none;
              }
            }

            @keyframes fadeInDown {
              0% {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
              }
              100% {
                opacity: 1;
                -webkit-transform: none;
                transform: none;
              }
            }

            /* Simple CSS3 Fade-in Animation */
            @-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
            @-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
            @keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

            .fadeIn {
              opacity:0;
              -webkit-animation:fadeIn ease-in 1;
              -moz-animation:fadeIn ease-in 1;
              animation:fadeIn ease-in 1;

              -webkit-animation-fill-mode:forwards;
              -moz-animation-fill-mode:forwards;
              animation-fill-mode:forwards;

              -webkit-animation-duration:1s;
              -moz-animation-duration:1s;
              animation-duration:1s;
            }

            .fadeIn.first {
              -webkit-animation-delay: 0.4s;
              -moz-animation-delay: 0.4s;
              animation-delay: 0.4s;
            }

            .fadeIn.second {
              -webkit-animation-delay: 0.6s;
              -moz-animation-delay: 0.6s;
              animation-delay: 0.6s;
            }

            .fadeIn.third {
              -webkit-animation-delay: 0.8s;
              -moz-animation-delay: 0.8s;
              animation-delay: 0.8s;
            }

            .fadeIn.fourth {
              -webkit-animation-delay: 1s;
              -moz-animation-delay: 1s;
              animation-delay: 1s;
            }

            /* Simple CSS3 Fade-in Animation */
            .underlineHover:after {
              display: block;
              left: 0;
              bottom: -10px;
              width: 0;
              height: 2px;
              background-color: #56baed;
              content: "";
              transition: width 0.2s;
            }

            .underlineHover:hover {
              color: #0d0d0d;
            }

            .underlineHover:hover:after{
              width: 100%;
            }

            /* OTHERS */

            *:focus {
                outline: none;
            } 

            #icon {
              width:60%;
            }

            #footer-black{
              /* position: fixed; */
              left: 0;
              bottom: 0;
              background-color:black;
              box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
              box-sizing: border-box;
              width: 100%;
              text-align: left;
              font: bold 16px sans-serif;
              padding: 25px 0;
              margin-top: 80px;
            }
        </style>

        <nav id="mainNav">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <!-- <a class="navbar-brand" href="#">WebSiteName</a>  -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                    </button>
                  </div>
                  <ul class="nav navbar-nav">
                    <li class="active"><a class="navbar-brand js-scroll-trigger" href="#home">Home</a></li>
                    <li><a class="nav-link js-scroll-trigger" href="#list-beasiswa">List Beasiswa</a></li>
                    <li><a class="nav-link js-scroll-trigger" href="#pengumuman">Pengumuman</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'registrasi:registrasi' %}" class="nav-link"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                    <!-- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
                  </ul>
                </div>
              </nav>
    </head>
    
    <body>
         <!-- LOGIN -->
         <div class="wrapper fadeInDown">
                <div id="formContent">
                  <!-- Tabs Titles -->
              
                  <!-- Icon -->
                  <div class="fadeIn first">
                    <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
                  </div>
              
                  <!-- Login Form -->
                  <form>
                    <input type="text" id="username" class="fadeIn second" name="login" placeholder="username">
                    <input type="password" id="password" class="fadeIn third" name="login" placeholder="password">
                    <input type="submit" class="fadeIn fourth" value="Log In">
                  </form>
              
                  <!-- Remind Passowrd -->
                  <div id="formFooter">
                    <a class="underlineHover" href="#">Forgot Password?</a>
                  </div>
              
                </div>
              </div>
                    </section>
                
<footer id="footer-black">
    <div>
        <div class="container">
            <div class="row">
                  <p>© Copyright 2018. K18Basdat. All Rights Reserved. <span class="pull-right"><a href="#">Privacy</a> | <a href="#">ToS</a> | <a href="#">Contact</a></span></p>
            </div>
          </div>
    </div>
</footer>
</body>
</html>